drop procedure THE_GRID.login
drop function THE_GRID.dameUserIDdni
drop function THE_GRID.dameUserIDcuit
drop trigger THE_GRID.inhabilitarUsuario
drop trigger THE_GRID.inhabilitarRoles
drop view THE_GRID.Estad_Productos
drop view THE_GRID.Estad_Facturacion
drop view THE_GRID.Estad_Calificaciones
drop view THE_GRID.Estad_Calificar
drop table THE_GRID.Oferta
drop table THE_GRID.Roles_x_Usuario
drop table THE_GRID.Administrador
drop table THE_GRID.Cliente
drop table THE_GRID.Empresa
drop table THE_GRID.Compra
drop table THE_GRID.Pregunta
drop table THE_GRID.RenglonFactura
drop table THE_GRID.Factura
drop table THE_GRID.Rubros_x_Publicacion
drop table THE_GRID.Publicacion
drop table THE_GRID.Usuario
drop table THE_GRID.Tipo_Usuario
drop table THE_GRID.Funcionalidades_x_Rol
drop table THE_GRID.Funcionalidad
drop table THE_GRID.Rol
drop table THE_GRID.Rubro
drop table THE_GRID.Visibilidad
drop table THE_GRID.Estado_Publicacion
drop table THE_GRID.Tipo_Publicacion
drop schema [THE_GRID]