drop table pruebasDeScript.dbo.TG_Preguntas
drop table pruebasDeScript.dbo.TG_Publicaciones_x_Rubro
drop table pruebasDeScript.dbo.TG_Compra
drop table pruebasDeScript.dbo.TG_Oferta
drop table pruebasDeScript.dbo.TG_Publicacion
drop table pruebasDeScript.dbo.TG_Direccion
drop table pruebasDeScript.dbo.TG_Informacion
drop table pruebasDeScript.dbo.TG_Caracteristicas_x_Rol
drop table pruebasDeScript.dbo.TG_Funcionalidades_x_Rol
drop table pruebasDeScript.dbo.TG_Roles_x_Usuario
drop table pruebasDeScript.dbo.TG_Factura
drop table pruebasDeScript.dbo.TG_Visibilidad
drop table pruebasDeScript.dbo.TG_Rubro
drop table pruebasDeScript.dbo.TG_Rol
drop table pruebasDeScript.dbo.TG_Usuario